Squeeze does not provide usr/include/linux/netfilter_ipv4/ip_queue.h
Triggers iptables package build error:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DXTABLES_LIBDIR=\"/lib/xtables\" -DXTABLES_INTERNAL -I../include -I../include -Wall -Waggregate-return -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes -Winline -pipe -g -O2 -c libipq.c  -fPIC -DPIC -o .libs/libipq.o
In file included from libipq.c:34:
../include/libipq/libipq.h:33:43: error: linux/netfilter_ipv4/ip_queue.h: No such file or directory
In file included from libipq.c:34:
../include/libipq/libipq.h:65: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
libipq.c: In function ‘ipq_set_mode’:
libipq.c:273: error: expected specifier-qualifier-list before ‘ipq_peer_msg_t’
libipq.c:279: error: ‘IPQM_MODE’ undeclared (first use in this function)
libipq.c:279: error: (Each undeclared identifier is reported only once
libipq.c:279: error: for each function it appears in.)
libipq.c:281: error: ‘struct <anonymous>’ has no member named ‘pm’
libipq.c:282: error: ‘struct <anonymous>’ has no member named ‘pm’
libipq.c: At top level:
libipq.c:308: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
libipq.c: In function ‘ipq_set_verdict’:
libipq.c:322: error: ‘ipq_peer_msg_t’ undeclared (first use in this function)
libipq.c:322: error: expected ‘;’ before ‘pm’
libipq.c:328: error: ‘IPQM_VERDICT’ undeclared (first use in this function)
libipq.c:330: error: ‘pm’ undeclared (first use in this function)
make[4]: *** [libipq.lo] Error 1

Add a local version here to fix build error.